### ISSUE TITLE
Doesn't seem to submit correct URL vars?

### ISSUE THREAD

**Issue by TXChetG** [lpmagnuson/discovery-tabbed-search#1]
So... I'm flying blind here with skim information from our librarians on implementing this new WorldCat search bar. Inserted the code, inserted our WorldCat information, however when I attempt to run a search, no search is actually completed. It just opens WorldCat and leaves me to search again. 

Any ideas?

**Comment by pshowell23** [comment]
@TXChetG aside from putting your library's info, did you change the code any? Which code are you using (search.html or dropdown/search.html)?

**Comment by TXChetG** [comment]
@pshowell23 I'm using the search.html.

I've attached what I'm using. If there's something I'm missing I'd love to know. :-D

[worldcat.txt](https://github.com/lpmagnuson/discovery-tabbed-search/files/413639/worldcat.txt)

**Comment by lpmagnuson** [comment]
Hey @TXChetG, it looks like the form action URL is going to your WorldCat local instance (doane.worldcat.org) instead of WorldCat Discovery.  WorldCat local uses different search query parameters.  If you want to use WorldCat Local, you'll need to change the input parameter name "queryString" to "q" for each of the search forms.  I think there are other parameters you'll probably want to test and change - WorldCat Local might use different search parameter syntax than WorldCat Discovery for format selection; I'm not 100% sure.  You can test the parameters by doing direct searches in WorldCat Local and checking the URL bar.

Alternatively, you could change the search form action URLs to WorldCat Discovery, which would look like this: doane.on.worldcat.org.  That depends on whether your library is "live" with WorldCat Discovery right now - it looks like your library home page still links to WorldCat Local.

Hope this helps.

**Comment by lpmagnuson** [comment]
@TXChetG I went ahead and plugged in some basic query parameters you'll  need for WorldCat Local on the various tabs in the file you'd sent.  Test it out and let me know if this is what you have in mind. 

[worldcat.txt](https://github.com/lpmagnuson/discovery-tabbed-search/files/413926/worldcat.txt)

**Comment by TXChetG** [comment]
@lpmagnuson Thanks to you, I now know that there are such things as Worldcat Local, and WorldCat Discovery. I'm fairly certain Discovery is what they want to connect with since they keep talking about their "new" system. 

I plugged in the Discovery URL you suggested, and that loads/populates just fine. The WorldCat search bar however isn't passing variables to the search URL. I'm looking into that now. 

Also the Public facing library page is definitely still on WorldCat Local. I have this implementation on our dev server. 

**Edit:** Wasn't passing Parameters since I targeted the wrong URL, again. However it's not passing the `databaseList` variable and that seems to be important.

**Comment by lpmagnuson** [comment]
@TXChetG Cool, let me know if I can help with anything else.  I did throw your original code with the action URL changed to WorldCat Discovery [here](http://www.palni.org/worldcat/palni/new/discovery-tabbed-search/search3.html), and it seems to be working, but let me know what's still not working as expected.

**Comment by TXChetG** [comment]
@lpmagnuson Thanks so much for your time today. 

Everything started moving smoothly once I updated the form action to `/search` rather than `/discovery` as I'd had it before. 

Truly appreciate it.
